name: Secrets Demo

on: [ workflow_dispatch ]

jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.SECRET_FROM_REPO }}
        name: Secret From Repo
      - run: echo ${{ vars.VAR_FROM_REPO }}
        name: Var From Repo
      - run: echo ${{ secrets.SECRET_FROM_ORG }}
        name: Secret From Org
